#!/usr/bin/env bash

file="$1"
username="$3"
ip="$2"
path="$4"

if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
elif [ "$#" -lt 4 ]; then
    scp "$file" "$username@$ip:~/"
    exit 1
fi
scp -r "$file" "$username@$ip:$path"