#!/usr/bin/env bash

sudo apt update
# installs ngix 
sudo apt-get -y install nginx
# allow it run on port 80
sudo ufw allow 'Nginx HTTP'

# create a static page content "Hello World"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# restarts the ngix server
sudo nginx service restart