#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
var="Best School"
i=0

while [ $i -lt 10 ]; do
    echo "$var"
     if [ $i == 8 ]; then
        echo "Hi"
    fi
    i=$((i + 1))
done